import { ServiceCategoryDTO } from './types';

export const defaultCategories: ServiceCategoryDTO[] = [
  {
    id: 'cat-plumber',
    name: 'Plumbing',
    slug: 'plumber',
    description: 'Pipe leakage, tap fitting, bathroom & sanitary',
    iconName: 'Wrench',
    colorScheme: 'teal',
    startingPrice: 199,
    activeWorkersCount: 4,
  },
  {
    id: 'cat-electrician',
    name: 'Electrician',
    slug: 'electrician',
    description: 'Wiring, switches, fan repair, inverter',
    iconName: 'Plug',
    colorScheme: 'blue',
    startingPrice: 249,
    activeWorkersCount: 3,
  },
  {
    id: 'cat-mason',
    name: 'Mason / Mistri',
    slug: 'mason',
    description: 'Tiles, plaster, brick wall construction',
    iconName: 'BrickWall',
    colorScheme: 'brick',
    startingPrice: 399,
    activeWorkersCount: 2,
  },
  {
    id: 'cat-carpenter',
    name: 'Carpenter',
    slug: 'carpenter',
    description: 'Furniture, doors, locks & wood repair',
    iconName: 'Saw',
    colorScheme: 'purple',
    startingPrice: 299,
    activeWorkersCount: 2,
  },
  {
    id: 'cat-painter',
    name: 'Painter',
    slug: 'painter',
    description: 'Interior/exterior wall painting & waterproofing',
    iconName: 'Palette',
    colorScheme: 'rose',
    startingPrice: 499,
    activeWorkersCount: 2,
  },
  {
    id: 'cat-ac',
    name: 'AC Repair',
    slug: 'ac-repair',
    description: 'AC gas refill, cooling check & servicing',
    iconName: 'AirVent',
    colorScheme: 'sky',
    startingPrice: 399,
    activeWorkersCount: 3,
  },
  {
    id: 'cat-appliance',
    name: 'Appliance Repair',
    slug: 'appliance-repair',
    description: 'Washing machine, fridge, microwave',
    iconName: 'Tv',
    colorScheme: 'indigo',
    startingPrice: 299,
    activeWorkersCount: 2,
  },
  {
    id: 'cat-cleaner',
    name: 'Deep Cleaning',
    slug: 'cleaner',
    description: 'Full home deep sanitization & kitchen scrubbing',
    iconName: 'Sparkles',
    colorScheme: 'green',
    startingPrice: 499,
    activeWorkersCount: 2,
  },
  {
    id: 'cat-ro',
    name: 'RO Purifier',
    slug: 'ro-technician',
    description: 'RO membrane, filter change & water purifier fix',
    iconName: 'Droplets',
    colorScheme: 'cyan',
    startingPrice: 249,
    activeWorkersCount: 2,
  },
  {
    id: 'cat-cctv',
    name: 'CCTV Security',
    slug: 'cctv-technician',
    description: 'CCTV camera installation & smart locks',
    iconName: 'Camera',
    colorScheme: 'slate',
    startingPrice: 350,
    activeWorkersCount: 2,
  },
  {
    id: 'cat-mechanic',
    name: 'Auto / Bike Mechanic',
    slug: 'mechanic',
    description: 'Doorstep bike & vehicle repair',
    iconName: 'Compass',
    colorScheme: 'amber',
    startingPrice: 199,
    activeWorkersCount: 3,
  },
  {
    id: 'cat-welder',
    name: 'Welder',
    slug: 'welder',
    description: 'Iron gates, grills & fabrication',
    iconName: 'Flame',
    colorScheme: 'slate',
    startingPrice: 300,
    activeWorkersCount: 1,
  },
];
