import { WorkerCardDTO, ServiceRequestDTO, ServiceCategoryDTO } from './types';
import { defaultCategories } from './categories-data';

export interface MockUser {
  id: string;
  name: string;
  email: string;
  phone?: string;
  role: 'CUSTOMER' | 'WORKER' | 'ADMIN';
  city: string;
  locality: string;
  passwordHash?: string;
  avatarUrl?: string | null;
  workerProfile?: any;
  customerProfile?: any;
}

// Initial In-Memory Seed Users
export const initialUsers: MockUser[] = [
  {
    id: 'user-admin',
    name: 'Sarthi Admin Staff',
    email: 'demo.admin@sarthi.local',
    phone: '+91 98765 00001',
    role: 'ADMIN',
    city: 'Prayagraj',
    locality: 'Civil Lines',
  },
  {
    id: 'user-customer',
    name: 'Priya Singh',
    email: 'demo.customer@sarthi.local',
    phone: '+91 98765 11111',
    role: 'CUSTOMER',
    city: 'Prayagraj',
    locality: 'Civil Lines',
    customerProfile: {
      defaultAddress: 'Flat 402, Ganga Heights, MG Marg, Civil Lines, Prayagraj',
    },
  },
  {
    id: 'user-worker-rahul',
    name: 'Rahul Kumar',
    email: 'demo.worker@sarthi.local',
    phone: '+91 98765 22222',
    role: 'WORKER',
    city: 'Prayagraj',
    locality: 'Civil Lines',
    workerProfile: {
      id: 'wp-rahul',
      primaryCategoryId: 'cat-electrician',
      bio: 'Certified master electrician with 8+ years experience in domestic and commercial electrical repairs, smart switchboards, and fan winding.',
      experienceYears: 8,
      startingPrice: 250,
      serviceRadiusKm: 12.0,
      rating: 4.9,
      reviewCount: 48,
      completedJobs: 128,
      responseRate: 99,
      isAvailable: true,
      isVerified: true,
      identityVerified: true,
      professionVerified: true,
      workingHours: '7:30 AM - 9:30 PM',
      emergency24x7: true,
      latitude: 25.4358,
      longitude: 81.8463,
      category: defaultCategories.find((c) => c.slug === 'electrician'),
      services: [
        {
          id: 'srv-1',
          customTitle: 'Ceiling Fan & Exhaust Fan Repair',
          price: 250,
          description: 'Complete inspection, capacitor replacement, wiring fix & hanging',
        },
        {
          id: 'srv-2',
          customTitle: 'Switchboard & Socket Installation',
          price: 199,
          description: 'Modular switch replacement, MCB tripping resolution',
        },
        {
          id: 'srv-3',
          customTitle: 'Inverter & Battery Wiring',
          price: 450,
          description: 'Dual line wiring, heavy inverter setup & earthing test',
        },
      ],
    },
  },
];

// Initial 12+ Seed Workers
export const initialWorkers: WorkerCardDTO[] = [
  {
    id: 'wp-rahul',
    userId: 'user-worker-rahul',
    name: 'Rahul Kumar',
    avatarUrl: null,
    categoryName: 'Electrician',
    categorySlug: 'electrician',
    city: 'Prayagraj',
    locality: 'Civil Lines',
    startingPrice: 250,
    rating: 4.9,
    reviewCount: 48,
    completedJobs: 128,
    experienceYears: 8,
    responseRate: 99,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: true,
    distanceKm: 1.8,
    matchReasons: ['Available Today', 'Fully Verified', 'Top Rated (4.9 ⭐)', '128+ jobs done'],
  },
  {
    id: 'wp-suresh',
    userId: 'user-worker-suresh',
    name: 'Suresh Kumar',
    avatarUrl: null,
    categoryName: 'Plumbing',
    categorySlug: 'plumber',
    city: 'Prayagraj',
    locality: 'Katra',
    startingPrice: 200,
    rating: 4.8,
    reviewCount: 32,
    completedJobs: 94,
    experienceYears: 6,
    responseRate: 96,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: true,
    distanceKm: 2.1,
    matchReasons: ['Available Today', 'Verified Pro', 'Nearby (< 2.5 km)'],
  },
  {
    id: 'wp-vinod',
    userId: 'user-worker-vinod',
    name: 'Vinod Mistri',
    avatarUrl: null,
    categoryName: 'Plumbing',
    categorySlug: 'plumber',
    city: 'Prayagraj',
    locality: 'Naini',
    startingPrice: 180,
    rating: 4.7,
    reviewCount: 21,
    completedJobs: 65,
    experienceYears: 5,
    responseRate: 95,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 4.2,
    matchReasons: ['Available Today', 'Verified Pro'],
  },
  {
    id: 'wp-anil',
    userId: 'user-worker-anil',
    name: 'Anil Sharma',
    avatarUrl: null,
    categoryName: 'Electrician',
    categorySlug: 'electrician',
    city: 'Prayagraj',
    locality: 'George Town',
    startingPrice: 220,
    rating: 4.8,
    reviewCount: 29,
    completedJobs: 87,
    experienceYears: 7,
    responseRate: 97,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 2.4,
    matchReasons: ['Available Today', 'Verified Pro', 'Top Rated'],
  },
  {
    id: 'wp-ramesh',
    userId: 'user-worker-ramesh',
    name: 'Ramesh Verma',
    avatarUrl: null,
    categoryName: 'Mason / Mistri',
    categorySlug: 'mason',
    city: 'Prayagraj',
    locality: 'Ashok Nagar',
    startingPrice: 450,
    rating: 4.9,
    reviewCount: 51,
    completedJobs: 142,
    experienceYears: 11,
    responseRate: 98,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 3.1,
    matchReasons: ['Available Today', 'Fully Verified', '142+ jobs done'],
  },
  {
    id: 'wp-arif',
    userId: 'user-worker-arif',
    name: 'Mohd. Arif',
    avatarUrl: null,
    categoryName: 'Carpenter',
    categorySlug: 'carpenter',
    city: 'Prayagraj',
    locality: 'Chowk',
    startingPrice: 300,
    rating: 4.8,
    reviewCount: 38,
    completedJobs: 110,
    experienceYears: 9,
    responseRate: 96,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 3.5,
    matchReasons: ['Available Today', 'Verified Pro'],
  },
  {
    id: 'wp-sunil',
    userId: 'user-worker-sunil',
    name: 'Sunil Pal',
    avatarUrl: null,
    categoryName: 'Painter',
    categorySlug: 'painter',
    city: 'Prayagraj',
    locality: 'Tagore Town',
    startingPrice: 450,
    rating: 4.7,
    reviewCount: 19,
    completedJobs: 58,
    experienceYears: 6,
    responseRate: 94,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 2.8,
    matchReasons: ['Available Today', 'Verified Pro'],
  },
  {
    id: 'wp-deepak',
    userId: 'user-worker-deepak',
    name: 'Deepak Maurya',
    avatarUrl: null,
    categoryName: 'AC & Cooling Repair',
    categorySlug: 'ac-repair',
    city: 'Prayagraj',
    locality: 'Civil Lines',
    startingPrice: 399,
    rating: 4.9,
    reviewCount: 84,
    completedJobs: 210,
    experienceYears: 10,
    responseRate: 99,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: true,
    distanceKm: 1.2,
    matchReasons: ['Available Today', '24x7 Emergency', 'Top Rated (4.9 ⭐)', '210+ jobs done'],
  },
  {
    id: 'wp-rajesh',
    userId: 'user-worker-rajesh',
    name: 'Rajesh Tiwari',
    avatarUrl: null,
    categoryName: 'Appliance Repair',
    categorySlug: 'appliance-repair',
    city: 'Prayagraj',
    locality: 'Allahpur',
    startingPrice: 299,
    rating: 4.8,
    reviewCount: 26,
    completedJobs: 76,
    experienceYears: 8,
    responseRate: 95,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 3.8,
    matchReasons: ['Available Today', 'Verified Pro'],
  },
  {
    id: 'wp-vikas',
    userId: 'user-worker-vikas',
    name: 'Vikas Gupta',
    avatarUrl: null,
    categoryName: 'RO Water Purifier',
    categorySlug: 'ro-technician',
    city: 'Prayagraj',
    locality: 'Mumfordganj',
    startingPrice: 249,
    rating: 4.9,
    reviewCount: 31,
    completedJobs: 89,
    experienceYears: 5,
    responseRate: 98,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 2.6,
    matchReasons: ['Available Today', 'Top Rated'],
  },
  {
    id: 'wp-amit',
    userId: 'user-worker-amit',
    name: 'Amit Srivastava',
    avatarUrl: null,
    categoryName: 'CCTV & Security',
    categorySlug: 'cctv-technician',
    city: 'Prayagraj',
    locality: 'Lukerganj',
    startingPrice: 350,
    rating: 4.8,
    reviewCount: 23,
    completedJobs: 64,
    experienceYears: 7,
    responseRate: 96,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 3.3,
    matchReasons: ['Available Today', 'Verified Pro'],
  },
  {
    id: 'wp-manoj',
    userId: 'user-worker-manoj',
    name: 'Manoj Yadav',
    avatarUrl: null,
    categoryName: 'Auto / Bike Mechanic',
    categorySlug: 'mechanic',
    city: 'Prayagraj',
    locality: 'Kareli',
    startingPrice: 199,
    rating: 4.7,
    reviewCount: 36,
    completedJobs: 102,
    experienceYears: 9,
    responseRate: 97,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: true,
    distanceKm: 4.0,
    matchReasons: ['Available Today', '24x7 Emergency'],
  },
  {
    id: 'wp-pooja',
    userId: 'user-worker-pooja',
    name: 'Pooja Devi',
    avatarUrl: null,
    categoryName: 'Deep Cleaning',
    categorySlug: 'cleaner',
    city: 'Prayagraj',
    locality: 'Civil Lines',
    startingPrice: 499,
    rating: 4.9,
    reviewCount: 44,
    completedJobs: 115,
    experienceYears: 6,
    responseRate: 99,
    isAvailable: true,
    isVerified: true,
    identityVerified: true,
    professionVerified: true,
    emergency24x7: false,
    distanceKm: 1.5,
    matchReasons: ['Available Today', 'Top Rated (4.9 ⭐)'],
  },
];

// Initial In-Memory Requests Store
export const inMemoryRequests: ServiceRequestDTO[] = [
  {
    id: 'req-past-1',
    customerId: 'user-customer',
    customerName: 'Priya Singh',
    customerPhone: '+91 98765 11111',
    workerId: 'user-worker-rahul',
    workerName: 'Rahul Kumar',
    categoryName: 'Electrician',
    problemTitle: 'Ceiling Fan Regulator Sparking & Noise',
    problemDescription: 'The 5-speed fan regulator was sparking whenever turned to speed 3 and fan was wobbling.',
    urgency: 'ASAP',
    scheduledTime: 'Immediate',
    locationAddress: 'Flat 402, Ganga Heights, MG Marg, Civil Lines, Prayagraj',
    locationCity: 'Prayagraj',
    locationLocality: 'Civil Lines',
    estimatedBudget: 350,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 22).toISOString(),
    timeline: [
      { id: 'tl-1', status: 'REQUESTED', note: 'Request placed by customer', createdAt: new Date(Date.now() - 3600000 * 24).toISOString() },
      { id: 'tl-2', status: 'ACCEPTED', note: 'Rahul Kumar accepted the request', createdAt: new Date(Date.now() - 3600000 * 23.8).toISOString() },
      { id: 'tl-3', status: 'ON_THE_WAY', note: 'Worker is traveling to location', createdAt: new Date(Date.now() - 3600000 * 23.5).toISOString() },
      { id: 'tl-4', status: 'ARRIVED', note: 'Worker reached the premises', createdAt: new Date(Date.now() - 3600000 * 23.2).toISOString() },
      { id: 'tl-5', status: 'IN_PROGRESS', note: 'Regulator replaced and fan balanced', createdAt: new Date(Date.now() - 3600000 * 23).toISOString() },
      { id: 'tl-6', status: 'COMPLETED', note: 'Job completed successfully', createdAt: new Date(Date.now() - 3600000 * 22).toISOString() },
    ],
    review: {
      id: 'rev-1',
      ratingOverall: 5.0,
      comment: 'Rahul arrived within 20 minutes! Replaced the faulty regulator cleanly and balanced our old ceiling fan. Extremely courteous, professional and fair pricing.',
      createdAt: new Date(Date.now() - 3600000 * 21.8).toISOString(),
    },
  },
];
